name: Generate Profile Summary Cards

on:
  schedule: # Runs once a day at midnight
    - cron: "0 0 * * *"
  workflow_dispatch: # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate GitHub Profile Summary Cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        with:
          USERNAME: ${{ github.repository_owner }}

      - name: Commit and Push summary cards
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add profile-summary-card-output || true
          git commit -m "Updated profile summary cards" || true
          git push
